### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Milan0718** [molnarg/com.ngbs.icon#10]
Cannot read properties of undefined (reading firmware) hiba üzenet jelenik meg, mi a teendő?
![IMG_0003](https://github.com/molnarg/com.ngbs.icon/assets/97552051/d5fead89-cbe1-482d-9ab6-c604f41e4d9a)

**Comment by molnarg** [comment]
Not sure if you got my email response in the diagnostics report. I've released a test version, pls check if it solves it: https://homey.app/en-hu/app/com.ngbs.icon/NGBS-iCON/test/

**Comment by Milan0718** [comment]
Thank you!
It is work

**Comment by molnarg** [comment]
Nice! Thanks for reporting the problem.
